# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:

import numpy as np


print(np.version.version)



2.1.3


'\n1.15.2\n'

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [5]:
a = np.random.randint(3, size=(2,3,5))
a

array([[[2, 1, 0, 2, 1],
        [1, 0, 0, 0, 0],
        [1, 2, 0, 2, 2]],

       [[1, 1, 0, 2, 0],
        [2, 0, 1, 1, 1],
        [0, 0, 1, 1, 0]]], dtype=int32)


### 4. Print a.


In [6]:
print(a)


[[[2 1 0 2 1]
  [1 0 0 0 0]
  [1 2 0 2 2]]

 [[1 1 0 2 0]
  [2 0 1 1 1]
  [0 0 1 1 0]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [11]:
b = np.ones((5,2,3))
b


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 6. Print b.


In [12]:
print(b)


Shape of b: (5, 2, 3)
Size of b: 30

Array b:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [ ]:
print(a.size)
print(b.size)



### 8. Are you able to add a and b? Why or why not?


In [30]:
a + b
### No because the dimensions of the arrays don't fit


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [35]:
c = b.transpose(1,2,0)
print(c)



[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [31]:
d = a + c
d


array([[[3., 2., 1., 3., 2.],
        [2., 1., 1., 1., 1.],
        [2., 3., 1., 3., 3.]],

       [[2., 2., 1., 3., 1.],
        [3., 1., 2., 2., 2.],
        [1., 1., 2., 2., 1.]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(d)

### It's literally the same sized matrix than a and c but with their values sumed

[[[3. 2. 1. 3. 2.]
  [2. 1. 1. 1. 1.]
  [2. 3. 1. 3. 3.]]

 [[2. 2. 1. 3. 1.]
  [3. 1. 2. 2. 2.]
  [1. 1. 2. 2. 1.]]]



### 12. Multiply a and c. Assign the result to e.


In [38]:
e = a * c
print(e)

[[[2. 1. 0. 2. 1.]
  [1. 0. 0. 0. 0.]
  [1. 2. 0. 2. 2.]]

 [[1. 1. 0. 2. 0.]
  [2. 0. 1. 1. 1.]
  [0. 0. 1. 1. 0.]]]




### 13. Does e equal to a? Why or why not?


In [ ]:
### Because c it's just a matrix full of ones 





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [43]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [46]:
f = np.empty((2,3,5))





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
# Asignar valores directamente basado en condiciones
f[d == d_min] = 0
f[d == d_max] = 100  
f[d == d_mean] = 50
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75



[1. 2. 3.]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
print(d)

print(f)

## yes

[[[3. 2. 1. 3. 2.]
  [2. 1. 1. 1. 1.]
  [2. 3. 1. 3. 3.]]

 [[2. 2. 1. 3. 1.]
  [3. 1. 2. 2. 2.]
  [1. 1. 2. 2. 1.]]]
[[[100.  75.   0. 100.  75.]
  [ 75.   0.   0.   0.   0.]
  [ 75. 100.   0. 100. 100.]]

 [[ 75.  75.   0. 100.   0.]
  [100.   0.  75.  75.  75.]
  [  0.   0.  75.  75.   0.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [70]:
f_str = f.astype(object)
f_str[f_str == 0] = "A"
f_str[f_str == 25] = "B"
f_str[f_str == 50] = "C"
f_str[f_str == 75] = "D"
f_str[f_str == 100] = "E"

f_str

array([[['E', 'D', 'A', 'E', 'D'],
        ['D', 'A', 'A', 'A', 'A'],
        ['D', 'E', 'A', 'E', 'E']],

       [['D', 'D', 'A', 'E', 'A'],
        ['E', 'A', 'D', 'D', 'D'],
        ['A', 'A', 'D', 'D', 'A']]], dtype=object)